spring:
  cloud:
    stream:
      bindings:
        orderOutput-0:
          destination: order-topic

        paymentOutput-0:
          destination: payment-topic
      kafka:
        binder:
          brokers: localhost:9092
#        producer:
#          key-serializer: org.apache.kafka.common.serialization.StringSerializer
#          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#          properties:
#            spring.json.trusted.packages: com.example.music_album.entity
#            spring.json.add.type.headers: true
#        consumer:
#          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#          properties:
#            spring.json.trusted.packages: com.example.music_album.entity
#            spring.json.add.type.headers: true
